project:
  type: website
  output-dir: docs

website:
  title: "Zhe Fang - MUSA 5080 Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      
      - text: "Weekly Notes"
        menu:
          - text: "All Notes"
            href: weekly-notes/index.html
          - text: "Week 1 - Course Intro"
            href: weekly-notes/week-01-notes.qmd
      
      - text: "Assignments"
        menu:
          - text: "Assignment 1"
            href: assignments/assignment1/assignment1.html
          - text: "Assignment 2"
            href: assignments/assignment2/Fang_Zhe_Assignment2.html
          - text: "Assignment 4"
            href: assignments/assignment4/Fang_Zhe_Assignment4.html
          - text: "Assignment 5"
            href: assignments/assignment5/HW5.html

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
